import { StyleSheet } from "react-native";

export default StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#F3F5F7",
    borderRadius: 18,
    padding: 0,
    alignItems: "stretch",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    position: "relative",
  },
  header: {
    backgroundColor: "#3498db",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingTop: 28,
    paddingBottom: 18,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 18,
    color: "#D6E0F0",
    textAlign: "center",
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "500",
    color: "#444",
    marginTop: 22,
    marginLeft: 18,
    marginBottom: 8,
  },
  summaryBox: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    marginHorizontal: 16,
    padding: 16,
    marginBottom: 18,
  },
  summaryLabel: {
    fontWeight: "600",
    fontSize: 16,
    color: "#222",
    marginTop: 8,
  },
  summaryValue: {
    fontSize: 15,
    color: "#6B7280",
    marginBottom: 2,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 18,
  },
  checkboxLabel: {
    fontSize: 14,
    color: "#444",
    marginLeft: 8,
    flex: 1,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginBottom: 18,
  },
  editButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#3498db",
    borderWidth: 2,
    borderRadius: 8,
    paddingVertical: 12,
    marginRight: 8,
    alignItems: "center",
  },
  editButtonText: {
    color: "#3498db",
    fontWeight: "bold",
    fontSize: 18,
  },
  confirmButton: {
    flex: 1,
    backgroundColor: "#3498db",
    borderRadius: 8,
    paddingVertical: 12,
    marginLeft: 8,
    alignItems: "center",
  },
  confirmButtonDisabled: {
    backgroundColor: "#A0AEC0",
  },
  confirmButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 18,
  },
  closeButton: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 2,
    padding: 4,
  },
});
